export const CROP_BUDGET_REQUEST = "CROP_BUDGET_REQUEST";
export const CROP_BUDGET_SUCCESS = "CROP_BUDGET_SUCCESS";
export const CROP_BUDGET_FAIL = "CROP_BUDGET_FAIL";
export const CROP_BUDGET_CLEAR_ERRORS = "CROP_BUDGET_CLEAR_ERRORS";
