export const SIMPLE_CROP_REQUEST = "SIMPLE_CROP_REQUEST";
export const SIMPLE_CROP_SUCCESS = "SIMPLE_CROP_SUCCESS";
export const SIMPLE_CROP_FAIL = "SIMPLE_CROP_FAIL";
export const SIMPLE_CROP_CLEAR_ERRORS = "SIMPLE_CROP_CLEAR_ERRORS";

export const ADVANCE_CROP_REQUEST = "ADVANCE_CROP_REQUEST";
export const ADVANCE_CROP_SUCCESS = "ADVANCE_CROP_SUCCESS";
export const ADVANCE_CROP_FAIL = "ADVANCE_CROP_FAIL";
export const ADVANCE_CROP_CLEAR_ERRORS = "ADVANCE_CROP_CLEAR_ERRORS";

export const FERTILIZER_REQUEST = "FERTILIZER_REQUEST";
export const FERTILIZER_SUCCESS = "FERTILIZER_SUCCESS";
export const FERTILIZER_FAIL = "FERTILIZER_FAIL";
export const FERTILIZER_CLEAR_ERRORS = "FERTILIZER_CLEAR_ERRORS";

export const PEST_REQUEST = "PEST_REQUEST";
export const PEST_SUCCESS = "PEST_SUCCESS";
export const PEST_FAIL = "PEST_FAIL";
export const PEST_CLEAR_ERRORS = "PEST_CLEAR_ERRORS";

export const CROP_DISEASE_REQUEST = "CROP_DISEASE_REQUEST";
export const CROP_DISEASE_SUCCESS = "CROP_DISEASE_SUCCESS";
export const CROP_DISEASE_FAIL = "CROP_DISEASE_FAIL";
export const CROP_DISEASE_CLEAR_ERRORS = "CROP_DISEASE_CLEAR_ERRORS";
