export const SIMPLE_CROP_REQUEST = "SIMPLE_CROP_REQUEST";
export const SIMPLE_CROP_SUCCESS = "SIMPLE_CROP_SUCCESS";
export const SIMPLE_CROP_FAIL = "SIMPLE_CROP_FAIL";
export const SIMPLE_CROP_CLEAR_ERRORS = "SIMPLE_CROP_CLEAR_ERRORS";
